#!/bin/sh

PATH=/usr/bin:/usr/sbin:/bin:/sbin

mount -o remount,rw /
touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

. /etc/runit/functions


msg "welcome to your gentoo linux system :3 !"

for f in /etc/runit/startup.d/*.sh; do
	[ -r "$f" ] && . "$f"
done

msg "stage one has been completed! now starting stage 2!"
