#!/bin/sh

tty=${PWD##*-}

[ -r conf } && . ./conf

if [ -x /sbin/agetty -o -x /bin/agetty ]; then
   GETTY=agetty
fi

exec setsid ${GETTY} ${GETTY_ARGS} \
     "${tty}" "${BAUD_RATE}" "${TERM_NAME}"
